name: Gene2
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - aom=3.9.1
  - asttokens=2.4.1
  - atk-1.0=2.38.0
  - aws-c-auth=0.7.22
  - aws-c-cal=0.7.1
  - aws-c-common=0.9.23
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.2
  - aws-c-io=0.14.10
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.6.0
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.27.3
  - aws-sdk-cpp=1.11.329
  - azure-core-cpp=1.12.0
  - azure-identity-cpp=1.8.0
  - azure-storage-blobs-cpp=12.11.0
  - azure-storage-common-cpp=12.6.0
  - azure-storage-files-datalake-cpp=12.10.0
  - binutils_impl_linux-64=2.40
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.32.2
  - ca-certificates=2024.7.4
  - cairo=1.18.0
  - curl=8.8.0
  - dav1d=1.2.1
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - expat=2.6.2
  - fftw=3.3.10
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1
  - fribidi=1.0.10
  - gcc_impl_linux-64=14.1.0
  - gdk-pixbuf=2.42.12
  - gflags=2.2.2
  - gfortran_impl_linux-64=14.1.0
  - ghostscript=10.03.1
  - giflib=5.2.2
  - glog=0.7.1
  - graphite2=1.3.13
  - graphviz=11.0.0
  - gsl=2.7
  - gtk2=2.24.33
  - gts=0.7.6
  - gxx_impl_linux-64=14.1.0
  - harfbuzz=8.5.0
  - icu=73.2
  - imagemagick=7.1.1_35
  - importlib-metadata=8.0.0
  - importlib_metadata=8.0.0
  - ipython=8.26.0
  - jbig=2.1
  - jedi=0.19.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libarrow=16.1.0
  - libarrow-acero=16.1.0
  - libarrow-dataset=16.1.0
  - libarrow-substrait=16.1.0
  - libavif16=1.1.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.8.0
  - libde265=1.0.15
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-devel_linux-64=14.1.0
  - libgcc-ng=14.1.0
  - libgd=2.3.3
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libgit2=1.8.1
  - libglib=2.80.3
  - libgomp=14.1.0
  - libgoogle-cloud=2.26.0
  - libgoogle-cloud-storage=2.26.0
  - libgrpc=1.62.2
  - libheif=1.17.6
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libopenblas=0.3.27
  - libparquet=16.1.0
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - librsvg=2.58.2
  - libsanitizer=14.1.0
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx-devel_linux-64=14.1.0
  - libstdcxx-ng=14.1.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libwebp=1.4.0
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - make=4.3
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlopt=2.7.1
  - openjpeg=2.5.2
  - openssl=3.3.1
  - orc=2.0.1
  - packaging=24.1
  - pandoc=3.2.1
  - pango=1.54.0
  - parso=0.8.4
  - pcre2=10.44
  - perl=5.32.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - pixman=0.43.2
  - pkg-config=0.29.2
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.47
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.18.0
  - python=3.10.14
  - python-dateutil=2.9.0
  - python_abi=3.10=4_cp310
  - r-abind=1.4_5
  - r-arrow=16.1.0
  - r-askpass=1.2.0
  - r-assertthat=0.2.1
  - r-babelgene
  - r-backports=1.5.0
  - r-base=4.3.3
  - r-base64enc=0.1_3
  - r-bit=4.0.5
  - r-bit64=4.0.5
  - r-boot=1.3_30
  - r-brew=1.0_10
  - r-brio=1.1.5
  - r-broom=1.0.6
  - r-bslib=0.7.0
  - r-cachem=1.1.0
  - r-callr=3.7.6
  - r-car=3.1_2
  - r-cardata=3.0_5
  - r-caret=6.0_94
  - r-cellranger=1.1.0
  - r-circlize=0.4.16
  - r-class=7.3_22
  - r-cli=3.6.3
  - r-clipr=0.8.0
  - r-clock=0.7.0
  - r-clue=0.3_65
  - r-cluster=2.1.6
  - r-codetools=0.2_20
  - r-colorspace=2.1_0
  - r-commonmark=1.9.1
  - r-conquer=1.3.3
  - r-corrplot=0.92
  - r-cowplot=1.1.3
  - r-cpp11=0.4.7
  - r-crayon=1.5.3
  - r-credentials=2.0.1
  - r-curl=5.2.1
  - r-data.table=1.15.4
  - r-desc=1.4.3
  - r-devtools=2.4.5
  - r-diagram=1.6.5
  - r-diffobj=0.3.5
  - r-digest=0.6.36
  - r-doparallel=1.0.17
  - r-downlit=0.4.4
  - r-dplyr=1.1.4
  - r-e1071=1.7_14
  - r-ellipsis=0.3.2
  - r-evaluate=0.24.0
  - r-fansi=1.0.6
  - r-farver=2.1.2
  - r-fastmap=1.2.0
  - r-fontawesome=0.5.2
  - r-forcats=1.0.0
  - r-foreach=1.5.2
  - r-foreign=0.8_87
  - r-fs=1.6.4
  - r-future=1.33.2
  - r-future.apply=1.11.2
  - r-generics=0.1.3
  - r-gert=2.0.1
  - r-getoptlong=1.0.5
  - r-ggnewscale=0.4.10
  - r-ggplot2=3.5.1
  - r-ggpubr=0.6.0
  - r-ggrepel=0.9.5
  - r-ggsci=3.2.0
  - r-ggsignif=0.6.4
  - r-gh=1.4.1
  - r-gitcreds=0.1.2
  - r-globaloptions=0.1.2
  - r-globals=0.16.3
  - r-glue=1.7.0
  - r-gower=1.0.1
  - r-gridextra=2.3
  - r-gtable=0.3.5
  - r-hardhat=1.4.0
  - r-haven=2.5.4
  - r-highr=0.11
  - r-hms=1.1.3
  - r-htmltools=0.5.8.1
  - r-htmlwidgets=1.6.4
  - r-httpuv=1.6.15
  - r-httr2=1.0.1
  - r-ini=0.3.1
  - r-ipred=0.9_14
  - r-isoband=0.2.7
  - r-iterators=1.0.14
  - r-jquerylib=0.1.4
  - r-jsonlite=1.8.8
  - r-kernsmooth=2.23_24
  - r-knitr=1.48
  - r-labeling=0.4.3
  - r-later=1.3.2
  - r-lattice=0.22_6
  - r-lava=1.7.3
  - r-lifecycle=1.0.4
  - r-listenv=0.9.1
  - r-lme4=1.1_35.5
  - r-lubridate=1.9.3
  - r-magick=2.8.3
  - r-magrittr=2.0.3
  - r-maptools=1.1_8
  - r-mass=7.3_60.0.1
  - r-matrix=1.6_5
  - r-matrixmodels=0.5_3
  - r-matrixstats=1.3.0
  - r-memoise=2.0.1
  - r-mgcv=1.9_1
  - r-mime=0.12
  - r-miniui=0.1.1.1
  - r-minqa=1.2.7
  - r-modelmetrics=1.2.2.2
  - r-msigdbr=7.5.1
  - r-munsell=0.5.1
  - r-nlme=3.1_165
  - r-nloptr=2.0.3
  - r-nnet=7.3_19
  - r-numderiv=2016.8_1.1
  - r-openssl=2.2.0
  - r-parallelly=1.37.1
  - r-patchwork=1.2.0
  - r-pbkrtest=0.5.2
  - r-pillar=1.9.0
  - r-pkgbuild=1.4.4
  - r-pkgconfig=2.0.3
  - r-pkgdown=2.1.0
  - r-pkgload=1.3.4
  - r-plyr=1.8.9
  - r-png=0.1_8
  - r-polynom=1.4_1
  - r-praise=1.0.0
  - r-prettyunits=1.2.0
  - r-proc=1.18.5
  - r-processx=3.8.4
  - r-prodlim=2024.06.25
  - r-profvis=0.3.8
  - r-progress=1.2.3
  - r-progressr=0.14.0
  - r-promises=1.3.0
  - r-proxy=0.4_27
  - r-ps=1.7.7
  - r-purrr=1.0.2
  - r-quantreg=5.98
  - r-r.methodss3=1.8.2
  - r-r.oo=1.26.0
  - r-r.utils=2.12.3
  - r-r6=2.5.1
  - r-ragg=1.3.2
  - r-rappdirs=0.3.3
  - r-rcmdcheck=1.4.0
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.0.12
  - r-rcpparmadillo=14.0.0_1
  - r-rcppeigen=0.3.4.0.0
  - r-readr=2.1.5
  - r-readxl=1.4.3
  - r-recipes=1.1.0
  - r-rematch=2.0.0
  - r-rematch2=2.1.2
  - r-remotes=2.5.0
  - r-reshape2=1.4.4
  - r-rio=1.1.1
  - r-rjson=0.2.21
  - r-rlang=1.1.4
  - r-rmarkdown=2.27
  - r-roxygen2=7.3.2
  - r-rpart=4.1.23
  - r-rprojroot=2.0.4
  - r-rstatix=0.7.2
  - r-rstudioapi=0.16.0
  - r-rversions=2.1.2
  - r-sass=0.4.9
  - r-scales=1.3.0
  - r-sessioninfo=1.2.2
  - r-shape=1.4.6.1
  - r-shiny=1.8.1.1
  - r-sourcetools=0.1.7_1
  - r-sp=2.1_4
  - r-sparsem=1.84
  - r-squarem=2021.1
  - r-stringi=1.8.4
  - r-stringr=1.5.1
  - r-survival=3.7_0
  - r-sys=3.4.2
  - r-systemfonts=1.1.0
  - r-testthat=3.2.1.1
  - r-textshaping=0.4.0
  - r-tibble=3.2.1
  - r-tidyr=1.3.1
  - r-tidyselect=1.2.1
  - r-timechange=0.3.0
  - r-timedate=4032.109
  - r-tinytex=0.51
  - r-tzdb=0.4.0
  - r-urlchecker=1.0.1
  - r-usethis=2.2.3
  - r-utf8=1.2.4
  - r-vctrs=0.6.5
  - r-viridislite=0.4.2
  - r-vroom=1.6.5
  - r-waldo=0.5.2
  - r-whisker=0.4.1
  - r-withr=3.0.0
  - r-writexl=1.5.0
  - r-xfun=0.45
  - r-xml=3.99_0.16.1
  - r-xml2=1.3.6
  - r-xopen=1.0.1
  - r-xtable=1.8_4
  - r-yaml=2.3.9
  - r-zip=2.3.1
  - rav1e=0.6.6
  - re2=2023.09.01
  - readline=8.2
  - s2n=1.4.17
  - sed=4.8
  - setuptools=70.3.0
  - six=1.16.0
  - snappy=1.2.1
  - stack_data=0.6.2
  - svt-av1=2.1.2
  - sysroot_linux-64=2.12
  - tk=8.6.13
  - tktable=2.10
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.43.0
  - x265=3.5
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-libxt=1.3.0
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
    - brainsmash==0.11.0
    - contourpy==1.2.1
    - cycler==0.12.1
    - debugpy==1.8.2
    - fonttools==4.53.1
    - ipykernel==6.14.0
    - joblib==1.3.2
    - jupyter-core==5.7.2
    - kiwisolver==1.4.5
    - matplotlib==3.8.2
    - nibabel==5.2.0
    - numpy==1.26.4
    - pandas==2.1.4
    - pillow==10.4.0
    - psutil==6.0.0
    - pyparsing==3.1.2
    - pytz==2024.1
    - pyzmq==26.0.3
    - scikit-learn==1.3.2
    - scipy==1.11.4
    - seaborn==0.12.2
    - threadpoolctl==3.5.0
    - tornado==6.4.1
    - tqdm==4.66.4
    - tzdata==2024.1
prefix: /n01dat01/kkwang/softwares/anaconda-3/envs/Gene2